### ISSUE TITLE
The touch screen does not work

### ISSUE THREAD

**Issue by BigBuge** [BigfootACA/device_nubia_nx729j#2] opened 2023-05-07 05:34 UTC
My phone model is NX729J， and version number is 2.26. I flashed twrp_recovery, but i can not control my phone for any action. But Fastboot mode work fine.
By the way, the command I entered is “fastboot flash recovery_b twrp.img && fastboot flash recovery_a twrp.img".

**Comment by JWnSC** [comment] 2023-05-12 11:29
> My phone model is NX729J， and version number is 2.26. I flashed twrp_recovery, but i can not control my phone for any action. But Fastboot mode work fine. By the way, the command I entered is “fastboot flash recovery_b twrp.img && fastboot flash recovery_a twrp.img".

Touchscreen works if your decrypted..I used ro2rw to disable encryption. Dfe neo should work also. This recovery won't work on an encrypted rom. It works fine (if decrypted) just a little slow. I just used it to restore super.img..device wouldn't boot do to custom adreno drivers😅 my fault.

**Comment by BigfootACA** [comment] 2023-06-15 14:15
this problem was caused by haptics, it has been fixed now
d1f9859bd859cc75de021c5dd44faf2db820fb3b

**Closed as completed by BigfootACA** 2023-06-15 14:15 UTC
